import React from "react";
import Head from "next/head";
const blogs = () => {
  return (
    <>
      <Head>
        <title>Hunting Coder | Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>blogs</div>
    </>
  );
};

export default blogs;
