import React from 'react'
import Head from "next/head";
const contact = () => {
  return (
    <>
      <Head>
        <title>Hunting Coder | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>contact</div>
    </>
  );
}

export default contact